// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_AP1_GregoryRodriguez.DAL;

#nullable disable

namespace P2_AP1_GregoryRodriguez.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("P2_AP1_GregoryRodriguez.Models.Componente", b =>
                {
                    b.Property<int>("ComponenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("ComponenteId");

                    b.ToTable("Componentes");

                    b.HasData(
                        new
                        {
                            ComponenteId = 1,
                            Descripcion = "Memoria 4GB",
                            Existencia = 1,
                            Precio = 1580.0
                        },
                        new
                        {
                            ComponenteId = 2,
                            Descripcion = "Disco SSD 120MB",
                            Existencia = 8,
                            Precio = 4200.0
                        },
                        new
                        {
                            ComponenteId = 3,
                            Descripcion = "Tarjeta de Video",
                            Existencia = 4,
                            Precio = 10000.0
                        });
                });

            modelBuilder.Entity("P2_AP1_GregoryRodriguez.Models.Pedidos", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("PedidoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("P2_AP1_GregoryRodriguez.Models.PedidosDetalle", b =>
                {
                    b.Property<int>("PedidoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponenteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("PedidoDetalleId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoDetalles");
                });

            modelBuilder.Entity("P2_AP1_GregoryRodriguez.Models.PedidosDetalle", b =>
                {
                    b.HasOne("P2_AP1_GregoryRodriguez.Models.Pedidos", null)
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("P2_AP1_GregoryRodriguez.Models.Pedidos", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
